--- 
name: "$(BuildDefinitionName)_$(SourceBranchName)_$(date:yyyyMMdd)$(rev:.r)"
stages: 
  - 
    displayName: "Provision resources to feature environment"
    jobs: 
      - 
        displayName: "Feature env provisioning job"
        job: feature_provisioning
        pool: 
          vmImage: ubuntu-latest
        steps: 
          - 
            displayName: "Feature environment provisioning"
            script: "echo provisioning to feature environment"
    stage: provision_to_feature_env
  - 
    displayName: "Provision resources to develop environment"
    jobs: 
      - 
        displayName: "Develop env provisioning job"
        job: develop_provisioning
        pool: 
          vmImage: ubuntu-latest
        steps: 
          - 
            displayName: "Develop environment provisioning"
            script: "echo provisioning to develop environment"
    stage: provision_to_develop_env
  - 
    displayName: "Provision resources to production environment"
    jobs: 
      - 
        displayName: "Prodduction env provisioning job"
        job: production_provisioning
        pool: 
          vmImage: ubuntu-latest
        steps: 
          - 
            displayName: "production environment provisioning"
            script: "echo provisioning to production environment"
    stage: provision_to_production_env
trigger: 
  branches: 
    include: 
      - "*"
variables: 
  BuildConfiguration: release
  BuildPlatform: "any cpu"
